export const SET_MODE = 'SET_MODE';
export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU'
export const SET_SUBMENU_STATUS = "SET_SUBMENU_STATUS"

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'