export const SET_NUMBER_LIST = 'SET_NUMBER_LIST';
// export const SET_AVAILABLE_NUMBERS = 'SET_AVAILABLE_NUMBERS';
export const SET_PROCCESING_MESSAGE = 'SET_PROCCESING_MESSAGE'
export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_ACTIVE_NUMBER = 'SET_ACTIVE_NUMBER'